(() => {
  const products = [
    { id: "focus", name: "Carnet Focus", category: "Organisation", price: 12.9, emoji: "📓", description: "Un carnet compact pour structurer vos idées et vos objectifs.", background: "linear-gradient(135deg, #553a62, #bf6f9e)" },
    { id: "stand", name: "Support Horizon", category: "Tech", price: 24.9, emoji: "💻", description: "Un support de bureau réglable pour un espace de travail plus confortable.", background: "linear-gradient(135deg, #1b4e67, #5e9cba)" },
    { id: "bottle", name: "Gourde Nomade", category: "Quotidien", price: 18.5, emoji: "💧", description: "Une gourde légère à emporter partout, au bureau comme en sortie.", background: "linear-gradient(135deg, #245051, #56a9a3)" },
    { id: "audio", name: "Écouteurs Pulse", category: "Tech", price: 39.9, emoji: "🎧", description: "Vos podcasts et playlists avec un format simple et nomade.", background: "linear-gradient(135deg, #30244e, #8567ad)" },
    { id: "desk", name: "Kit Bureau Calme", category: "Organisation", price: 28.0, emoji: "🗂️", description: "Des accessoires assortis pour clarifier votre espace de travail.", background: "linear-gradient(135deg, #55452a, #c59752)" },
    { id: "light", name: "Lampe Aura", category: "Maison", price: 32.5, emoji: "💡", description: "Une lumière d’ambiance douce pour vos lectures et vos soirées.", background: "linear-gradient(135deg, #513c27, #d5a664)" }
  ];
  const currency = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
  const storageKey = "sng_boutique_cart";
  let activeCategory = "Tous";
  let searchTerm = "";
  let cart = JSON.parse(localStorage.getItem(storageKey) || "[]");
  const grid = document.querySelector("#product-grid"); const categoryList = document.querySelector("#category-list"); const count = document.querySelector("#products-count");
  const cartPanel = document.querySelector("#cart-panel"); const cartScrim = document.querySelector("#cart-scrim"); const cartItems = document.querySelector("#cart-items");
  const saveCart = () => localStorage.setItem(storageKey, JSON.stringify(cart));
  const cartQuantity = () => cart.reduce((sum, item) => sum + item.quantity, 0);
  function renderCategories() { ["Tous", ...new Set(products.map((product) => product.category))].forEach((category) => { const button = document.createElement("button"); button.className = `category-button${category === activeCategory ? " is-active" : ""}`; button.type = "button"; button.textContent = category; button.addEventListener("click", () => { activeCategory = category; renderCategories(); renderProducts(); }); categoryList.append(button); }); }
  function visibleProducts() { const term = searchTerm.trim().toLocaleLowerCase("fr"); return products.filter((product) => (activeCategory === "Tous" || product.category === activeCategory) && (!term || `${product.name} ${product.category} ${product.description}`.toLocaleLowerCase("fr").includes(term))); }
  function renderProducts() { const visible = visibleProducts(); grid.innerHTML = ""; count.textContent = `${visible.length} produit${visible.length > 1 ? "s" : ""}`; if (!visible.length) { grid.innerHTML = '<p class="empty-products">Aucun produit ne correspond à votre recherche.</p>'; return; } visible.forEach((product) => { const card = document.createElement("article"); card.className = "shop-card"; card.innerHTML = `<div class="product-visual" style="--product-background:${product.background}" aria-hidden="true">${product.emoji}</div><div class="product-content"><span class="product-category">${product.category}</span><h3>${product.name}</h3><p>${product.description}</p><div class="product-bottom"><strong class="product-price">${currency.format(product.price)}</strong><button class="add-button" type="button" data-product-id="${product.id}">Ajouter au panier</button></div></div>`; grid.append(card); }); }
  function updateCart() { const quantity = cartQuantity(); document.querySelector("#cart-count").textContent = quantity; document.querySelector("#cart-total").textContent = currency.format(cart.reduce((sum, item) => sum + item.price * item.quantity, 0)); document.querySelector("#checkout-button").disabled = !quantity; cartItems.innerHTML = ""; if (!quantity) { cartItems.innerHTML = '<p class="cart-empty">Votre panier est vide.<br />Ajoutez un produit pour le retrouver ici.</p>'; return; } cart.forEach((item) => { const row = document.createElement("div"); row.className = "cart-item"; row.innerHTML = `<div><div class="cart-item-name">${item.name}</div><div class="cart-item-meta">${currency.format(item.price)} × ${item.quantity}</div></div><div class="quantity-controls"><button type="button" data-action="decrease" data-id="${item.id}" aria-label="Retirer un ${item.name}">−</button><span>${item.quantity}</span><button type="button" data-action="increase" data-id="${item.id}" aria-label="Ajouter un ${item.name}">+</button></div>`; cartItems.append(row); }); }
  function addProduct(id) { const product = products.find((item) => item.id === id); const item = cart.find((cartItem) => cartItem.id === id); if (item) item.quantity += 1; else cart.push({ ...product, quantity: 1 }); saveCart(); updateCart(); }
  function changeQuantity(id, amount) { const item = cart.find((cartItem) => cartItem.id === id); if (!item) return; item.quantity += amount; cart = cart.filter((cartItem) => cartItem.quantity > 0); saveCart(); updateCart(); }
  function setCartOpen(open) { cartPanel.classList.toggle("is-open", open); cartScrim.classList.toggle("is-visible", open); cartPanel.setAttribute("aria-hidden", String(!open)); document.querySelector("#cart-toggle").setAttribute("aria-expanded", String(open)); }
  document.querySelector("#product-search").addEventListener("input", (event) => { searchTerm = event.target.value; renderProducts(); });
  grid.addEventListener("click", (event) => { const button = event.target.closest("[data-product-id]"); if (button) addProduct(button.dataset.productId); });
  cartItems.addEventListener("click", (event) => { const button = event.target.closest("[data-action]"); if (button) changeQuantity(button.dataset.id, button.dataset.action === "increase" ? 1 : -1); });
  document.querySelector("#cart-toggle").addEventListener("click", () => setCartOpen(true)); document.querySelector("#cart-close").addEventListener("click", () => setCartOpen(false)); cartScrim.addEventListener("click", () => setCartOpen(false));
  document.querySelector("#checkout-button").addEventListener("click", () => alert("Votre sélection est prête. La finalisation sera bientôt disponible."));
  renderCategories(); renderProducts(); updateCart();
})();
